### ISSUE TITLE
vscode cannot build firmware, nor can it install library files

### ISSUE THREAD

**Issue by SwingW** [Aceinna/platform-aceinna_imu#17]
Libraries: Could not install library
PIO Core Call Error: "Library Storage: C:\\Users\\Swing_23\\.platformio\\lib\r\nLibraryManager: Installing id=7066 @ ^1.0.6\r\nDownloading...\r\n\n\nError: Please read http://bit.ly/package-manager-ioerror\r\nError: Traceback (most recent call last):\r\n File \"c:\\users\\swing_23\\.platformio\\penv\\lib\\site-packages\\urllib3\\response.py\", line 425, in _error_catcher\r\n yield\r\n File \"c:\\users\\swing_23\\.platformio\\penv\\lib\\site-packages\\urllib3\\response.py\", line 507, in read\r\n data = self._fp.read(amt) if not fp_closed else b\"\"\r\n File

**Comment by ivankravets** [comment]
Do you use a Proxy? Did you configured it in VSCode? https://docs.platformio.org/en/latest/integration/ide/vscode.html#proxy-server-support

**Comment by SwingW** [comment]
Yes, I use a proxy, but I still cannot download the library and install the firmware‘






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ivan Kravets"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 凌晨2:26
收件人:&nbsp;"Aceinna/platform-aceinna_imu"<platform-aceinna_imu@noreply.github.com&gt;;
抄送:&nbsp;"不止平凡"<2460613245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Aceinna/platform-aceinna_imu] vscode cannot build firmware, nor can it install library files (#17)





 
Do you use a Proxy? Did you configured it in VSCode? https://docs.platformio.org/en/latest/integration/ide/vscode.html#proxy-server-support

**Comment by ivankravets** [comment]
Could you open PlatformIO IDE Terminal and type 
```
pio lib -g 7066
```

Do you see any errors?

**Comment by SwingW** [comment]
Yes, I use a proxy, but I still cannot download the library and install the firmware‘





------------------ 原始邮件 ------------------
发件人:&nbsp;"Ivan Kravets"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 凌晨2:26
收件人:&nbsp;"Aceinna/platform-aceinna_imu"<platform-aceinna_imu@noreply.github.com&gt;;
抄送:&nbsp;"不止平凡"<2460613245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Aceinna/platform-aceinna_imu] vscode cannot build firmware, nor can it install library files (#17)





 
Do you use a Proxy? Did you configured it in VSCode? https://docs.platformio.org/en/latest/integration/ide/vscode.html#proxy-server-support

**Comment by ivankravets** [comment]
See https://github.com/Aceinna/platform-aceinna_imu/issues/17#issuecomment-619373843

**Comment by SwingW** [comment]
PS C:\Users\Swing_23\Documents\PlatformIO\Projects\RAWDATA> pio lib -g 7066
Usage: pio lib [OPTIONS] COMMAND [ARGS]...
Try "pio lib -h" for help.

Error: No such command "7066".

**Comment by ivankravets** [comment]
Sorry,
```
pio lib -g install 7066
```

**Comment by SwingW** [comment]
PS C:\Users\Swing_23\Documents\PlatformIO\Projects\RAWDATA> pio lib -g install 7066
Library Storage: C:\Users\Swing_23\.platformio\lib
LibraryManager: Installing id=7066
Error: Please read http://bit.ly/package-manager-ioerror
Error: Traceback (most recent call last):
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "E:\python3.7.7\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "E:\python3.7.7\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "E:\python3.7.7\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded with url: http://dl.platformio.org/libraries/archives/70/28375.tar.gz (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 154, in lib_install
    library, silent=silent, interactive=interactive, force=force
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 280, in install
    force=force,
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 700, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 130, in _install_from_piorepo
    requirements,
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 480, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 195, in download
    raise e
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 179, in download
    fd = FileDownloader(url, dest_dir)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\downloader.py", line 42, in __init__
    verify=sys.version_info >= (2, 7, 9),
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded with url: http://dl.platformio.org/libraries/archives/70/28375.tar.gz (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by SwingW** [comment]
PS C:\Users\Swing_23\Documents\PlatformIO\Projects\RAWDATA> pio lib -g install 7066
Library Storage: C:\Users\Swing_23\.platformio\lib
LibraryManager: Installing id=7066
Error: Please read http://bit.ly/package-manager-ioerror
Error: Traceback (most recent call last):
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "E:\python3.7.7\lib\http\client.py", line 1344, in getresponse
    response.begin()
  File "E:\python3.7.7\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "E:\python3.7.7\lib\http\client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded with url: http://dl.platformio.org/libraries/archives/70/28375.tar.gz (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 154, in lib_install
    library, silent=silent, interactive=interactive, force=force
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 280, in install
    force=force,
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 700, in install
    pkg_dir = self._install_from_piorepo(name, requirements)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 130, in _install_from_piorepo
    requirements,
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 480, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 195, in download
    raise e
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 179, in download
    fd = FileDownloader(url, dest_dir)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\platformio\downloader.py", line 42, in __init__
    verify=sys.version_info >= (2, 7, 9),
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\swing_23\.platformio\penv\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded with url: http://dl.platformio.org/libraries/archives/70/28375.tar.gz (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
https://docs.platformio.org/en/latest/integration/ide/vscode.html#proxy-server-support

Proxy settings were not set correctly. How did you set them? Via environment varaibles or via VSCode?

**Comment by SwingW** [comment]
Through the vscode settings, this is my vscode settings.json file: 
"http.proxyAuthorization": null,
"http.proxy": "http://127.0.0.1:1080",
"http.proxyStrictSSL": false

**Comment by SwingW** [comment]
Hi, I would like to ask, if the Aceinna OpenRTK330L Module Open Source Firmware Library is manually installed in which directory, and how can its project source program recognize its corresponding header file




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ivan Kravets"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 晚上9:22
收件人:&nbsp;"Aceinna/platform-aceinna_imu"<platform-aceinna_imu@noreply.github.com&gt;;
抄送:&nbsp;"不止平凡"<2460613245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Aceinna/platform-aceinna_imu] vscode cannot build firmware, nor can it install library files (#17)





 
https://docs.platformio.org/en/latest/integration/ide/vscode.html#proxy-server-support
 
Proxy settings were not set correctly. How did you set them? Via environment varaibles or via VSCode?

**Comment by ivankravets** [comment]
Is this proxy without login/passowrd? Without authentication? "HTTPConnectionPool(host='127.0.0.1', port=1080): Max retries exceeded", Python can't connect ot proxy server.

**Comment by SwingW** [comment]
I followed the tutorial on the Internet, but it still doesn't seem to work, I am currently trying to manually install the firmware library，if the Aceinna OpenRTK330L Module Open Source Firmware Library is manually installed in which directory, and how can its project source program recognize its corresponding header file

**Comment by ivankravets** [comment]
https://github.com/Aceinna/platform-aceinna_imu/issues/17#issuecomment-619572142

**Comment by SwingW** [comment]
I use Shadowsocks proxy, just configure the local Socks5 address: 127.0.0.1 and port: 1080 in vscode, but it still does not work

**Comment by SwingW** [comment]
When I click the build button, the vscode terminal prompts Error: Please read http://bit.ly/package-manager-ioerror, so I followed the suggested solutions, but solutions 1-3 will not work, so I am Try solution 4

**Comment by ivankravets** [comment]
Could you test this?
```
python -c "import requests; print(requests.get('https://api.platformio.org/stats').text)"
```

**Comment by SwingW** [comment]
PS C:\Users\Swing_23\Documents\PlatformIO\Projects\200426-204615-RAWDATA> python -c "import requests; print(requests.get('https://api.platformio.org/stats').text)"
{"frameworks": 20, "boards": 806, "platforms": 35, "libs": 7268, "mcus": 336, "libexamples": 31785}

**Comment by ivankravets** [comment]
Hm... Did you run it in PlatformIO IDE Terminal? Where ran `pio lib -g install 7066` ?

**Comment by ivankravets** [comment]
Could you try again `pio lib -g install 7066`?

**Comment by SwingW** [comment]
in PlatformIO IDE Terminal？

**Comment by ivankravets** [comment]
VSCode > Left Side Bar/ActivityBAr > PlatformIO 👽  > Open PlatformIO CLI
```
pio lib -g install 7066
```

**Comment by SwingW** [comment]
Yes, I am running the above command in this terminal,and the following is the result of its operation,（maybe i need to wait a few minutes ):
PS C:\Users\Swing_23\Documents\PlatformIO\Projects\200426-204615-RAWDATA> pio lib -g install 7066
Library Storage: C:\Users\Swing_23\.platformio\lib

**Comment by SwingW** [comment]
The firmware library cannot be installed successfully. After using the command, it has been in the "generating ..."

**Comment by ivankravets** [comment]
I don’t understand you. Please provide screenshot

**Comment by SwingW** [comment]
![1](https://user-images.githubusercontent.com/45917104/80316534-006add80-8831-11ea-9a30-b7fe0b217691.png)

**Comment by SwingW** [comment]
![2](https://user-images.githubusercontent.com/45917104/80316617-563f8580-8831-11ea-95df-c02657e58535.png)

**Comment by ivankravets** [comment]
This is not our text "generating...". Could you run `cmd.exe` in this terminal and then `pio lib -g install 7066`?

**Comment by SwingW** [comment]
![1](https://user-images.githubusercontent.com/45917104/80493759-632ab900-8998-11ea-9c02-10a32431ce1e.png)
It still doesn't work

**Comment by ivankravets** [comment]
Could you contact us at `support` dog `platformio ` dot `org`?

**Comment by SwingW** [comment]
No matter whether I run the install library command in the vscode terminal or cmd.exe, I will install the firmware library and some packages manually. After importing the latest version of the project, the compilation is successful and I can finally burn the code into my development In the board. Finally, I want to say thank you very much for your help

**Comment by SwingW** [comment]
No matter running the install library command in the vscode terminal or cmd.exe, it will make mistakes, so I took the manual installation of the firmware library and some packages. After importing the latest version of the project, the compilation was successful, and finally the code can be burned into my Development board. Finally, I want to say thank you very much for your help

**Comment by SwingW** [comment]
No matter running the install library command in the vscode terminal or cmd.exe, it will make mistakes, so I took the manual installation of the firmware library and some packages. After importing the latest version of the project, the compilation was successful, and finally the code can be burned into my The development board is in, next I will develop the next step, and finally, I would like to say thank you very much for your help

**Comment by ivankravets** [comment]
We, at PlatformIO, would like to reproduce this issue on our side. Could you mail me directly to me@ikravets.com?
